server:
  port: 8111

spring:
  application:
    name: zuul-server
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://121.37.30.244:8761/eureka/
  instance:
    instance-id: http://121.37.30.244:8111
    prefer-ip-address: true
zuul:
  routes:
    sale:
      path: /test/**
      service-id: server-invoker

